### ISSUE TITLE
Manually building FAILS

### ISSUE THREAD

**Issue by Stoppedwumm** [drizzle-mizzle/Character-Engine-Discord#28]
I recommend changing to let the guys who wants to host to run

```bash
sudo docker compose up
```

**Comment by cha0sbuster** [comment]
This happened to me too. The issue for me was that the manual hosting guide tells you to use .NET 7, when in fact Character Engine has since been updated to .NET 8.
If Docker works, this is probably your issue, as a recently closed issue ended up being caused by the dockerfile *also* being out of date.
